[tool.poetry]
name = "computer vision with cctv"
version = "0.1.0"
description = ""
authors = ["Laith-Rasheed <laithrasheed747@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
notebook = "^7.4.2"
ipykernel = "^6.29.5"
huggingface-hub = "^0.31.2"
opencv-python = "^4.11.0.86"
matplotlib = "^3.10.3"
seaborn = "^0.13.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
